services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "4000:443"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5050:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  dbdata: