// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using libraryAPI.EfCore;

#nullable disable

namespace libraryAPI.Migrations
{
    [DbContext(typeof(EF_DataContext))]
    partial class EF_DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("libraryAPI.EfCore.Author", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("name", "date_of_birth");

                    b.ToTable("author");
                });

            modelBuilder.Entity("libraryAPI.EfCore.Book", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date_of_first_publication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("edition")
                        .HasColumnType("integer");

                    b.Property<string>("original_language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("name", "date_of_first_publication");

                    b.ToTable("book");
                });

            modelBuilder.Entity("libraryAPI.EfCore.Relation", b =>
                {
                    b.Property<string>("bookname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("bookdate_of_first_publication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("authorname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("authordate_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("bookname", "bookdate_of_first_publication", "authorname", "authordate_of_birth");

                    b.HasIndex("authorname", "authordate_of_birth");

                    b.ToTable("relation");
                });

            modelBuilder.Entity("libraryAPI.EfCore.Relation", b =>
                {
                    b.HasOne("libraryAPI.EfCore.Author", "author")
                        .WithMany()
                        .HasForeignKey("authorname", "authordate_of_birth")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("libraryAPI.EfCore.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookname", "bookdate_of_first_publication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("author");

                    b.Navigation("book");
                });
#pragma warning restore 612, 618
        }
    }
}
